import { NextRequest, NextResponse } from 'next/server'
import { analyzeProposal, AnalysisResult } from '@/lib/analysis-engine'

// Sample proposal text for demo purposes (same as results route)
const sampleProposalText = `
We are pleased to submit this proposal in response to your RFP dated December 1, 2024.
ABC Construction has been an industry leader providing quality products and services for over 25 years.

Thank you for the opportunity to present our qualifications. Our experienced team of professionals
is dedicated to delivering the highest quality work on every project. We pride ourselves on our
proven track record and commitment to excellence.

As a trusted partner in the construction industry, we offer comprehensive solutions with competitive pricing.
Our full-service approach ensures seamless project delivery from start to finish.

We are committed to quality and strive to exceed expectations on every project. Our innovative solutions
and cutting-edge technology, combined with our state-of-the-art equipment, positions us as the partner of choice
for clients seeking world-class construction services.

Our long-term relationships with clients demonstrate our customer-centric approach. We leverage our
years of experience to utilize best practices and deliver value-added solutions.

Moving forward, we look forward to working with you to become your strategic partner. In order to
demonstrate our commitment to this project, we have assembled a team of experienced professionals
with unparalleled expertise in commercial construction.

Our robust and scalable approach, combined with our proactive project management, ensures we will
deliver end-to-end solutions that exceed your expectations. At the end of the day, it goes without
saying that we are the best-in-class solution provider you need.

Please see attached pricing schedule for our competitive rates. We are confident our pricing
represents excellent value for the scope of work described.

Thank you again for considering ABC Construction. We endeavor to earn your business and aim to
deliver second to none results. We seek to build a long-term partnership with your organization.
`

// In-memory cache reference (would share with results route in production)
const analysisCache: Record<string, { result: AnalysisResult; text: string }> = {}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params

  if (!id) {
    return NextResponse.json(
      { success: false, error: 'Missing result ID' },
      { status: 400 }
    )
  }

  // Get or generate analysis
  let text = sampleProposalText
  let result: AnalysisResult

  if (analysisCache[id]) {
    text = analysisCache[id].text
    result = analysisCache[id].result
  } else {
    result = analyzeProposal(text)
    analysisCache[id] = { result, text }
  }

  // Generate revised proposal by applying all fixes
  let revisedText = text

  // Sort issues by position descending so replacements don't affect earlier positions
  const sortedIssues = [...result.issues].sort((a, b) => b.position - a.position)

  // Track what we've already fixed to avoid double-fixes
  const fixedPhrases = new Set<string>()

  for (const issue of sortedIssues) {
    if (fixedPhrases.has(issue.phrase)) continue
    fixedPhrases.add(issue.phrase)

    // Replace the commodity phrase with the suggested replacement
    // The suggestedReplacement already contains the context with the fix applied
    // So we need to extract just the better example and use it
    const betterText = issue.betterExample.replace(/^["'"']|["'"']$/g, '').trim()

    // Replace first occurrence of the phrase
    revisedText = revisedText.replace(issue.phrase, betterText)
  }

  // Clean up extra whitespace
  revisedText = revisedText
    .replace(/\n{3,}/g, '\n\n')
    .trim()

  // Format as a document
  const formattedDocument = `
═══════════════════════════════════════════════════════════════
REVISED PROPOSAL
Generated by Proposal Analyzer
═══════════════════════════════════════════════════════════════

Original Commodity Score: ${result.score}/100 (${result.scoreLabel})
Issues Fixed: ${result.totalIssues}

═══════════════════════════════════════════════════════════════

${revisedText}

═══════════════════════════════════════════════════════════════
CHANGES MADE:
═══════════════════════════════════════════════════════════════

${sortedIssues.map((issue, i) => `
${i + 1}. [${issue.severity.toUpperCase()}] ${issue.category} - ${issue.subcategory}
   BEFORE: "${issue.phrase}"
   AFTER:  ${issue.betterExample}
`).join('\n')}

═══════════════════════════════════════════════════════════════
Next Steps:
1. Review each change in context
2. Customize examples with your specific data/projects
3. Run through the analyzer again to check your score

Generated by Proposal Analyzer | leefuhr.com
═══════════════════════════════════════════════════════════════
`.trim()

  return NextResponse.json({
    success: true,
    revisedProposal: formattedDocument,
    originalScore: result.score,
    issuesFixed: result.totalIssues,
    downloadFilename: `revised-proposal-${id}.txt`
  })
}
